### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by ComanderP** [tjammer/raylib-ocaml#45] opened 2024-09-08 14:20 UTC
Hi,

I recently attempted to install the `raylib` package on a Windows machine using opam 2.2, which now includes native Windows support. Unfortunately, the installation failed, and I'm not knowledgeable enough on opam to find a straightforward way to fix it.

Given that opam 2.2 introduced native Windows compatibility, I was wondering if there are any plans to add or improve support for Windows within `raylib-ocaml`. It would be fantastic to have this working on Windows as it would allow native compillation for Windows more easily.

Is there any way I could assist with testing or contributing towards Windows compatibility?

Thanks!

**Comment by tjammer** [comment] 2024-09-08 19:49
Thanks for bringing this up!
`raylib-ocaml` certainly builds for window (see https://github.com/tjammer/raylib-ocaml/issues/45), but I haven't kept up with the latest windows support changes since I don't have a windows machine anymore.
There used to be an extra opam repo for windows which has been deprecated for quite some time. I'll see what I can find out in the discord.

**Comment by tjammer** [comment] 2024-09-08 19:53
Could you paste the error log for you failed installation?

**Comment by ComanderP** [comment] 2024-09-08 19:59
Thanks for the quick reply! Here's the output I got trying to install raylib on a fresh switch through opam on Windows:
```powershell
PowerShell 7.4.5
System32
➜ opam switch list
#  switch   compiler                                                                        description
→  default  arch-x86_64.1,ocaml-base-compiler.5.2.0,ocaml-options-vanilla.1,system-mingw.1  ocaml >= 4.05.0
System32
➜ opam install raylib
The following actions will be performed:
=== install 8 packages
  ∗ bigarray-compat   1.1.0  [required by ctypes]
  ∗ csexp             1.5.2  [required by dune-configurator]
  ∗ ctypes            0.23.0 [required by raylib]
  ∗ dune              3.16.0 [required by raylib]
  ∗ dune-configurator 3.16.0 [required by raylib]
  ∗ integers          0.7.0  [required by raylib]
  ∗ raylib            1.3.0
  ∗ stdlib-shims      0.3.0  [required by integers]

Proceed with ∗ 8 installations? [y/n] y

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫
⬇ retrieved bigarray-compat.1.1.0  (https://opam.ocaml.org/cache)
⬇ retrieved csexp.1.5.2  (https://opam.ocaml.org/cache)
⬇ retrieved ctypes.0.23.0  (https://opam.ocaml.org/cache)
⬇ retrieved integers.0.7.0  (https://opam.ocaml.org/cache)
⬇ retrieved stdlib-shims.0.3.0  (https://opam.ocaml.org/cache)
⬇ retrieved raylib.1.3.0  (https://opam.ocaml.org/cache)
⬇ retrieved dune.3.16.0, dune-configurator.3.16.0  (https://opam.ocaml.org/cache)
∗ installed dune.3.16.0
∗ installed stdlib-shims.0.3.0
∗ installed bigarray-compat.1.1.0
∗ installed csexp.1.5.2
∗ installed integers.0.7.0
∗ installed dune-configurator.3.16.0
∗ installed ctypes.0.23.0
[ERROR] The compilation of raylib.1.3.0 failed at "dune build -p raylib -j 7 @install".

#=== ERROR while compiling raylib.1.3.0 =======================================#
# context     2.2.1 | win32/x86_64 | ocaml.5.2.0 | https://opam.ocaml.org#5ced20d683d7ac5cb4ba6b9468b14458fb69a213
# path        ~\AppData\Local\opam\default\.opam-switch\build\raylib.1.3.0
# command     ~\AppData\Local\opam\default\bin\dune.exe build -p raylib -j 7 @install
# exit-code   1
# env-file    ~\AppData\Local\opam\log\raylib-33512-a37aef.env
# output-file ~\AppData\Local\opam\log\raylib-33512-a37aef.out
### output ###
# c_generated_functions.c:3581:36: warning: passing argument 1 of 'TextReplace' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
# [...]
#       |                                    ^~~~~
# vendor/raylib/src/raylib.h:1468:31: note: expected 'char *' but argument is of type 'const char *'
#  1468 | RLAPI char *TextReplace(char *text, const char *replace, const char *by);                   // Replace text string (WARNING: memory must be freed!)
#       |                         ~~~~~~^~~~
# c_generated_functions.c: In function 'raylib_stub_399_TextAppend':
# c_generated_functions.c:3597:15: warning: passing argument 1 of 'TextAppend' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
#  3597 |    TextAppend(x3623, x3624, x3625);
#       |               ^~~~~
# vendor/raylib/src/raylib.h:1472:29: note: expected 'char *' but argument is of type 'const char *'
#  1472 | RLAPI void TextAppend(char *text, const char *append, int *position);                       // Append text at specific position and move cursor!
#       |                       ~~~~~~^~~~



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫
┌─ The following actions failed
│ λ build raylib 1.3.0
└─
┌─ The following changes have been performed
│ ∗ install bigarray-compat   1.1.0
│ ∗ install csexp             1.5.2
│ ∗ install ctypes            0.23.0
│ ∗ install dune              3.16.0
│ ∗ install dune-configurator 3.16.0
│ ∗ install integers          0.7.0
│ ∗ install stdlib-shims      0.3.0
└─

The former state can be restored with:
    C:\Users\prbop\AppData\Local\Microsoft\WinGet\Links\opam.exe switch import
"C:\\Users\\prbop\\AppData\\Local\\opam\\default\\.opam-switch\\backup\\state-20240908141040.export"
```

**Comment by tjammer** [comment] 2024-09-08 20:24
Could you add the whole output, at `~\AppData\Local\opam\log\raylib-33512-a37aef.out` please?

Does one need to install opengl libs on windows or do they come pre-installed?

**Comment by ComanderP** [comment] 2024-09-08 21:07
Here it is:
```sh
(cd _build/default/src/c && C:\PATH_Programs\mingw64\bin\unix2dos.exe vendor/raylib/src/config.h)
unix2dos: converting file vendor/raylib/src/config.h to DOS format...
File "src/c/dune", lines 114-140, characters 0-815:
114 | (rule
115 |  (alias build-raylib)
116 |  (targets libraylib.a dllraylib.dll)
.....
138 |     (run make -C vendor/raylib/src clean)
139 |     (run make -C vendor/raylib/src RAYLIB_LIBTYPE=SHARED -j 8)
140 |     (copy vendor/raylib/src/raylib.dll dllraylib.dll)))))
(cd _build/default/src/c && C:\Users\prbop\AppData\Local\opam\.cygwin\root\bin\patch.exe --binary -sp1) < _build/default/src/c/enable_jpg.patch
1 out of 1 hunk FAILED -- saving rejects to file vendor/raylib/src/config.h.rej
(cd _build/default/src/c && C:\Users\prbop\AppData\Local\opam\default\bin\x86_64-w64-mingw32-gcc.exe -O2 -fno-strict-aliasing -fwrapv -mms-bitfields -O2 -fno-strict-aliasing -fwrapv -mms-bitfields -g -I C:/Users/prbop/AppData/Local/opam/default/lib/ocaml -I C:/Users/prbop/AppData/Local/opam/default/lib/ocaml\str -I C:\Users\prbop\AppData\Local\opam\default\lib\bigarray-compat -I C:\Users\prbop\AppData\Local\opam\default\lib\ctypes -I C:\Users\prbop\AppData\Local\opam\default\lib\ctypes\stubs -I C:\Users\prbop\AppData\Local\opam\default\lib\integers -I C:\Users\prbop\AppData\Local\opam\default\lib\stdlib-shims -I functions -I types -I vendor/raylib/src -o c_generated_functions.o -c c_generated_functions.c)
c_generated_functions.c: In function 'raylib_stub_46_GetClipboardText':
c_generated_functions.c:259:17: warning: initialization discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
  259 |    char* x175 = GetClipboardText();
      |                 ^~~~~~~~~~~~~~~~
c_generated_functions.c: In function 'raylib_stub_111_UnloadFileData':
c_generated_functions.c:693:19: warning: passing argument 1 of 'UnloadFileData' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
  693 |    UnloadFileData(x523);
      |                   ^~~~
In file included from c_generated_functions.c:1:
vendor/raylib/src/raylib.h:1099:42: note: expected 'unsigned char *' but argument is of type 'const char *'
 1099 | RLAPI void UnloadFileData(unsigned char *data);                   // Unload file data allocated by LoadFileData()
      |                           ~~~~~~~~~~~~~~~^~~~
c_generated_functions.c: In function 'raylib_stub_115_UnloadFileText':
c_generated_functions.c:721:19: warning: passing argument 1 of 'UnloadFileText' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
  721 |    UnloadFileText(x547);
      |                   ^~~~
vendor/raylib/src/raylib.h:1103:33: note: expected 'char *' but argument is of type 'const char *'
 1103 | RLAPI void UnloadFileText(char *text);                            // Unload file text data allocated by LoadFileText()
      |                           ~~~~~~^~~~
c_generated_functions.c: In function 'raylib_stub_116_SaveFileText':
c_generated_functions.c:728:36: warning: passing argument 2 of 'SaveFileText' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
  728 |    _Bool x553 = SaveFileText(x551, x552);
      |                                    ^~~~
vendor/raylib/src/raylib.h:1104:53: note: expected 'char *' but argument is of type 'const char *'
 1104 | RLAPI bool SaveFileText(const char *fileName, char *text);        // Save text data to file (write), string must be '\0' terminated, returns true on success
      |                                               ~~~~~~^~~~
c_generated_functions.c: In function 'raylib_stub_393_TextCopy':
c_generated_functions.c:3552:25: warning: passing argument 1 of 'TextCopy' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
 3552 |    int x3584 = TextCopy(x3582, x3583);
      |                         ^~~~~
vendor/raylib/src/raylib.h:1463:26: note: expected 'char *' but argument is of type 'const char *'
 1463 | RLAPI int TextCopy(char *dst, const char *src);                                             // Copy one string to another, returns bytes copied
      |                    ~~~~~~^~~
c_generated_functions.c: In function 'raylib_stub_397_TextReplace':
c_generated_functions.c:3581:36: warning: passing argument 1 of 'TextReplace' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
 3581 |    char const* x3610 = TextReplace(x3607, x3608, x3609);
      |                                    ^~~~~
vendor/raylib/src/raylib.h:1468:31: note: expected 'char *' but argument is of type 'const char *'
 1468 | RLAPI char *TextReplace(char *text, const char *replace, const char *by);                   // Replace text string (WARNING: memory must be freed!)
      |                         ~~~~~~^~~~
c_generated_functions.c: In function 'raylib_stub_399_TextAppend':
c_generated_functions.c:3597:15: warning: passing argument 1 of 'TextAppend' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
 3597 |    TextAppend(x3623, x3624, x3625);
      |               ^~~~~
vendor/raylib/src/raylib.h:1472:29: note: expected 'char *' but argument is of type 'const char *'
 1472 | RLAPI void TextAppend(char *text, const char *append, int *position);                       // Append text at specific position and move cursor!
      |                       ~~~~~~^~~~
```

About the second question, I'm not sure because I'm not familiar with how it works but I think they should be installed as part of my graphics drivers from what I read online, otherwise Windows comes with `opengl32.dll` but that only supports till version 1.1 of opengl.

**Comment by tjammer** [comment] 2024-09-09 19:46
It's really strange that this patch won't apply on your build, because in the CI builds it does

```
(cd _build/default/src/c && "C:\Program Files\Git\usr\bin\unix2dos.exe" vendor/raylib/src/config.h)
unix2dos: converting file vendor/raylib/src/config.h to DOS format...
(cd _build/default/src/c && "C:\Program Files\Git\usr\bin\unix2dos.exe" vendor/raygui/src/raygui.h)
unix2dos: converting file vendor/raygui/src/raygui.h to DOS format...
(cd _build/default/src/c && D:\cygwin\bin\patch.exe --binary -p1) < _build/default/src/c/enable_jpg.patch
```

**Comment by ComanderP** [comment] 2024-09-09 20:01
It's really weird. I also tried installing opam on another Windows PC I have, and it also fails to build. The error seems similar to the other one, I think. Maybe there's something else I need to install for it to work?

```sh
File "src/c/dune", line 127, characters 9-17:
127 |     (run unix2dos vendor/raylib/src/config.h)
               ^^^^^^^^
Error: Program unix2dos not found in the tree or in PATH
 (context: default)
(cd _build/default/src/c && C:\Users\prbop\AppData\Local\opam\default\bin\x86_64-w64-mingw32-gcc.exe -O2 -fno-strict-aliasing -fwrapv -mms-bitfields -O2 -fno-strict-aliasing -fwrapv -mms-bitfields -g -I C:/Users/prbop/AppData/Local/opam/default/lib/ocaml -I C:/Users/prbop/AppData/Local/opam/default/lib/ocaml\str -I C:\Users\prbop\AppData\Local\opam\default\lib\bigarray-compat -I C:\Users\prbop\AppData\Local\opam\default\lib\ctypes -I C:\Users\prbop\AppData\Local\opam\default\lib\ctypes\stubs -I C:\Users\prbop\AppData\Local\opam\default\lib\integers -I C:\Users\prbop\AppData\Local\opam\default\lib\stdlib-shims -I functions -I types -I vendor/raylib/src -o c_generated_functions.o -c c_generated_functions.c)
c_generated_functions.c: In function 'raylib_stub_46_GetClipboardText':
c_generated_functions.c:259:17: warning: initialization discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
  259 |    char* x175 = GetClipboardText();
      |                 ^~~~~~~~~~~~~~~~
c_generated_functions.c: In function 'raylib_stub_111_UnloadFileData':
c_generated_functions.c:693:19: warning: passing argument 1 of 'UnloadFileData' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
  693 |    UnloadFileData(x523);
      |                   ^~~~
In file included from c_generated_functions.c:1:
vendor/raylib/src/raylib.h:1099:42: note: expected 'unsigned char *' but argument is of type 'const char *'
 1099 | RLAPI void UnloadFileData(unsigned char *data);                   // Unload file data allocated by LoadFileData()
      |                           ~~~~~~~~~~~~~~~^~~~
c_generated_functions.c: In function 'raylib_stub_115_UnloadFileText':
c_generated_functions.c:721:19: warning: passing argument 1 of 'UnloadFileText' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
  721 |    UnloadFileText(x547);
      |                   ^~~~
vendor/raylib/src/raylib.h:1103:33: note: expected 'char *' but argument is of type 'const char *'
 1103 | RLAPI void UnloadFileText(char *text);                            // Unload file text data allocated by LoadFileText()
      |                           ~~~~~~^~~~
c_generated_functions.c: In function 'raylib_stub_116_SaveFileText':
c_generated_functions.c:728:36: warning: passing argument 2 of 'SaveFileText' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
  728 |    _Bool x553 = SaveFileText(x551, x552);
      |                                    ^~~~
vendor/raylib/src/raylib.h:1104:53: note: expected 'char *' but argument is of type 'const char *'
 1104 | RLAPI bool SaveFileText(const char *fileName, char *text);        // Save text data to file (write), string must be '\0' terminated, returns true on success
      |                                               ~~~~~~^~~~
c_generated_functions.c: In function 'raylib_stub_393_TextCopy':
c_generated_functions.c:3552:25: warning: passing argument 1 of 'TextCopy' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
 3552 |    int x3584 = TextCopy(x3582, x3583);
      |                         ^~~~~
vendor/raylib/src/raylib.h:1463:26: note: expected 'char *' but argument is of type 'const char *'
 1463 | RLAPI int TextCopy(char *dst, const char *src);                                             // Copy one string to another, returns bytes copied
      |                    ~~~~~~^~~
c_generated_functions.c: In function 'raylib_stub_397_TextReplace':
c_generated_functions.c:3581:36: warning: passing argument 1 of 'TextReplace' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
 3581 |    char const* x3610 = TextReplace(x3607, x3608, x3609);
      |                                    ^~~~~
vendor/raylib/src/raylib.h:1468:31: note: expected 'char *' but argument is of type 'const char *'
 1468 | RLAPI char *TextReplace(char *text, const char *replace, const char *by);                   // Replace text string (WARNING: memory must be freed!)
      |                         ~~~~~~^~~~
c_generated_functions.c: In function 'raylib_stub_399_TextAppend':
c_generated_functions.c:3597:15: warning: passing argument 1 of 'TextAppend' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
 3597 |    TextAppend(x3623, x3624, x3625);
      |               ^~~~~
vendor/raylib/src/raylib.h:1472:29: note: expected 'char *' but argument is of type 'const char *'
 1472 | RLAPI void TextAppend(char *text, const char *append, int *position);                       // Append text at specific position and move cursor!
      |                       ~~~~~~^~~~
```

**Comment by tjammer** [comment] 2024-09-09 20:21
In that case `unix2dos` is missing. It all my cygwin installations it came preinstalled (I think), but you should be able to install it.
In the first log, the program is found and runs successfully. And yet the patch doesn't apply.

**Comment by tjammer** [comment] 2024-09-09 20:22
In the latest CI run (https://github.com/tjammer/raylib-ocaml/actions/runs/10780574784), I deleted the `unix2dos` uses and the patch still applies. Maybe it isn't needed at all?

**Comment by tjammer** [comment] 2024-09-09 20:23
Could you try to build `raylib-ocaml` from this commit? https://github.com/tjammer/raylib-ocaml/commit/e17f9700d3ebddf0f58157a5f9fb9031d762d350

**Comment by ComanderP** [comment] 2024-09-09 20:51
Tried building it on the 1st machine and still errors out, although it also complains about line endings now.

```sh
File "src/c/dune", lines 114-138, characters 0-722:
114 | (rule
115 |  (alias build-raylib)
116 |  (targets libraylib.a dllraylib.dll)
.....
136 |     (run make -C vendor/raylib/src clean)
137 |     (run make -C vendor/raylib/src RAYLIB_LIBTYPE=SHARED -j 8)
138 |     (copy vendor/raylib/src/raylib.dll dllraylib.dll)))))
(cd _build/default/src/c && C:\Users\prbop\AppData\Local\opam\.cygwin\root\bin\patch.exe --binary -p1) < _build/default/src/c/enable_jpg.patch
patching file vendor/raylib/src/config.h
Hunk #1 FAILED at 148 (different line endings).
1 out of 1 hunk FAILED -- saving rejects to file vendor/raylib/src/config.h.rej
(cd _build/default/src/c && C:\Users\prbop\AppData\Local\opam\default\bin\x86_64-w64-mingw32-gcc.exe -O2 -fno-strict-aliasing -fwrapv -mms-bitfields -O2 -fno-strict-aliasing -fwrapv -mms-bitfields -g -I C:/Users/prbop/AppData/Local/opam/default/lib/ocaml -I C:/Users/prbop/AppData/Local/opam/default/lib/ocaml\str -I C:\Users\prbop\AppData\Local\opam\default\lib\bigarray-compat -I C:\Users\prbop\AppData\Local\opam\default\lib\ctypes -I C:\Users\prbop\AppData\Local\opam\default\lib\ctypes\stubs -I C:\Users\prbop\AppData\Local\opam\default\lib\integers -I C:\Users\prbop\AppData\Local\opam\default\lib\stdlib-shims -I functions -I types -I vendor/raylib/src -o c_generated_functions.o -c c_generated_functions.c)
c_generated_functions.c: In function 'raylib_stub_46_GetClipboardText':
c_generated_functions.c:259:17: warning: initialization discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
  259 |    char* x175 = GetClipboardText();
      |                 ^~~~~~~~~~~~~~~~
c_generated_functions.c: In function 'raylib_stub_111_UnloadFileData':
c_generated_functions.c:693:19: warning: passing argument 1 of 'UnloadFileData' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
  693 |    UnloadFileData(x523);
      |                   ^~~~
In file included from c_generated_functions.c:1:
vendor/raylib/src/raylib.h:1099:42: note: expected 'unsigned char *' but argument is of type 'const char *'
 1099 | RLAPI void UnloadFileData(unsigned char *data);                   // Unload file data allocated by LoadFileData()
      |                           ~~~~~~~~~~~~~~~^~~~
c_generated_functions.c: In function 'raylib_stub_115_UnloadFileText':
c_generated_functions.c:721:19: warning: passing argument 1 of 'UnloadFileText' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
  721 |    UnloadFileText(x547);
      |                   ^~~~
vendor/raylib/src/raylib.h:1103:33: note: expected 'char *' but argument is of type 'const char *'
 1103 | RLAPI void UnloadFileText(char *text);                            // Unload file text data allocated by LoadFileText()
      |                           ~~~~~~^~~~
c_generated_functions.c: In function 'raylib_stub_116_SaveFileText':
c_generated_functions.c:728:36: warning: passing argument 2 of 'SaveFileText' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
  728 |    _Bool x553 = SaveFileText(x551, x552);
      |                                    ^~~~
vendor/raylib/src/raylib.h:1104:53: note: expected 'char *' but argument is of type 'const char *'
 1104 | RLAPI bool SaveFileText(const char *fileName, char *text);        // Save text data to file (write), string must be '\0' terminated, returns true on success
      |                                               ~~~~~~^~~~
c_generated_functions.c: In function 'raylib_stub_393_TextCopy':
c_generated_functions.c:3552:25: warning: passing argument 1 of 'TextCopy' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
 3552 |    int x3584 = TextCopy(x3582, x3583);
      |                         ^~~~~
vendor/raylib/src/raylib.h:1463:26: note: expected 'char *' but argument is of type 'const char *'
 1463 | RLAPI int TextCopy(char *dst, const char *src);                                             // Copy one string to another, returns bytes copied
      |                    ~~~~~~^~~
c_generated_functions.c: In function 'raylib_stub_397_TextReplace':
c_generated_functions.c:3581:36: warning: passing argument 1 of 'TextReplace' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
 3581 |    char const* x3610 = TextReplace(x3607, x3608, x3609);
      |                                    ^~~~~
vendor/raylib/src/raylib.h:1468:31: note: expected 'char *' but argument is of type 'const char *'
 1468 | RLAPI char *TextReplace(char *text, const char *replace, const char *by);                   // Replace text string (WARNING: memory must be freed!)
      |                         ~~~~~~^~~~
c_generated_functions.c: In function 'raylib_stub_399_TextAppend':
c_generated_functions.c:3597:15: warning: passing argument 1 of 'TextAppend' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
 3597 |    TextAppend(x3623, x3624, x3625);
      |               ^~~~~
vendor/raylib/src/raylib.h:1472:29: note: expected 'char *' but argument is of type 'const char *'
 1472 | RLAPI void TextAppend(char *text, const char *append, int *position);                       // Append text at specific position and move cursor!
      |                       ~~~~~~^~~~
```

**Comment by tjammer** [comment] 2024-09-09 21:00
Meh. The line endings are the reason for using `unix2dos`. I'll set up a windows workspace tomorrow and try to see if I can reproduce it.

**Comment by ComanderP** [comment] 2024-09-09 21:05
Alright, thank you! (as a side note, I installed `unix2dos` on my second machine and the problem still remains)

**Comment by tjammer** [comment] 2024-09-13 20:22
I haven't forgotten. Although I still don't understand why the patch won't apply on your machine. The usual mingw programs seem to be available and usually `patch --binary` deals with the headache related to line endings. Do you have any idea why the patch doesn't work?

An alternative might be to do the patching in OCaml during the build, instead of relying on the `patch` program.

**Comment by ComanderP** [comment] 2024-09-13 21:58
Hey, no worries, not really in a rush haha. I asked a friend of mine to check if the problem also occurs on his PC and it does. Unfortunatelly, I have no idea why it doesn't work.

**Comment by tjammer** [comment] 2024-09-14 21:26
Could you try bb4f817f70f3bc793b78eda8d8818d10fc221b8c? Still needs `unix2dos`

**Comment by ComanderP** [comment] 2024-09-17 21:36
The error stays the same. Maybe I'm installing it incorrectly? I used opam pin on the branch you specified just in case.

**Comment by tjammer** [comment] 2024-09-23 21:26
Sound correct. If you've pinned the branch before maybe an `opam update` is needed.

Another try: I'm now doing the patching in OCaml instead in the shell 64ceded331233c5ee17ae149d763bba70bab8634

**Comment by ComanderP** [comment] 2024-09-24 11:33
It works! I've managed to build a simple raylib app (just a simple window) but didn't test much. Although, `raygui` still suffers from the previous problem.

**Comment by tjammer** [comment] 2024-09-24 15:06
Perfect! I've changed the last uses of `patch` to the OCaml one, the latest commit should finally work.

I'll prepare a release later today.

**Comment by ComanderP** [comment] 2024-09-24 17:09
Thank you so much for your work into making this work! Honestly wish I could have done more.

**Comment by gdiazlo** [comment] 2024-10-05 15:07
It worked for me too. But raygui lib is still using unix2dos.

**Comment by tjammer** [comment] 2024-10-05 20:50
Thanks for mentioning it, I indeed forgot to update that package.
The fixed raygui package is part of the release now, PR to opam is underway (https://github.com/ocaml/opam-repository/pull/26679)

**Comment by tjammer** [comment] 2024-10-07 19:32
Raygui build should be fixed as well. Feel free to comment / reopen if it still doesn't work.

**Closed by tjammer** 2024-10-07 19:32 UTC
